### ISSUE TITLE
Верстка страницы "каталог"

### ISSUE THREAD

**Issue by agareev** [kursomir/Reader-iOS#16]

**Comment by basavind** [comment]
![_ -06](https://cloud.githubusercontent.com/assets/1267239/18610750/b5a04a78-7d2c-11e6-8b08-327ff0bab63d.png)
![_ -01 1](https://cloud.githubusercontent.com/assets/1267239/18610751/b74e76a6-7d2c-11e6-9c15-0a83b3563d04.png)
